const MARKER_LENGTH = 1;
const NUMBER = 0x00;
const BOOLEAN = 0x01;
const STRING = 0x02;
const OBJECT = 0x03;
const MOVIECLIP = 0x04;
const NULL = 0x05;
const UNDEFINED = 0x06;
const REFERENCE = 0x07;
const ECMA_ARRAY = 0x08;
const OBJECT_END = 0x09;
const STRICT_ARRAY = 0x0A;
const DATE = 0x0B;
const LONG_STRING = 0x0C;
const UNSUPPORTED = 0x0D;
const RECORDSET = 0x0E;
const XML_DOCUMENT = 0x0F;
const TYPED_OBJECT = 0x10;
const AVMPLUS_OBJECT = 0x11;

module.exports = {
	MARKER_LENGTH,
	NUMBER,
	BOOLEAN,
	STRING,
	OBJECT,
	MOVIECLIP,
	NULL,
	UNDEFINED,
	REFERENCE,
	ECMA_ARRAY,
	OBJECT_END,
	STRICT_ARRAY,
	DATE,
	LONG_STRING,
	UNSUPPORTED,
	RECORDSET,
	XML_DOCUMENT,
	TYPED_OBJECT,
	AVMPLUS_OBJECT,
};
